# Generated by Django 4.0.1 on 2022-02-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_add_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_blogmodel',
            name='image',
            field=models.ImageField(upload_to='my image/%y/%m/%d'),
        ),
    ]
